- name: Setup SSH
  run: |
    mkdir -p ~/.ssh

    echo "Testing secrets..."

    echo "${{ secrets.SERVER_USER }}"
    echo "${{ secrets.SERVER_IP }}"

    echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -c

    echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa

    chmod 600 ~/.ssh/id_rsa

    ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts