name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for containers
        run: sleep 10

      - name: Test API endpoint
        run: curl http://localhost/users

      - name: Stop containers
        run: docker compose down